version: "3.9"

services:
  optimizador:
    build: .
    container_name: optimizador-rutas
    restart: always
    env_file: .env
    ports:
      - "8004:8000"  # ‚Üê PUERTO 8004
    volumes:
      - .:/app